// test-fixtures/demo.jsx
// JSX demo
import { useState } from 'react';

function Animal({ name, sound }) {
  return <li>{name} says {sound}</li>;
}

export default function Demo() {
  const [animals, setAnimals] = useState([
    { name: 'Cat', sound: 'meow' },
    { name: 'Dog', sound: 'woof' },
  ]);

  return (
    <div className="demo">
      <h1>Hello, World!</h1>
      <ul>
        {animals.map(a => (
          <Animal key={a.name} name={a.name} sound={a.sound} />
        ))}
      </ul>
    </div>
  );
}

// test-fixtures/demo.vue
<script setup lang="ts">
// Vue demo
import { ref, computed } from 'vue'

interface Animal {
  name: string
  sound: string
}

const animals = ref<Animal[]>([
  { name: 'Cat', sound: 'meow' },
  { name: 'Dog', sound: 'woof' },
])

const greeting = computed(() => `Hello from ${animals.value.length} animals!`)
</script>

<template>
  <div class="demo">
    <h1>{{ greeting }}</h1>
    <ul>
      <li v-for="animal in animals" :key="animal.name">
        {{ animal.name }} says {{ animal.sound }}
      </li>
    </ul>
  </div>
</template>

<style scoped>
.demo {
  font-family: sans-serif;
  padding: 1rem;
}
</style>
